name: Update GitHub Activity

on:
  schedule:
    - cron: '8 */3 * * *'
  workflow_dispatch:

jobs:
  update-github-activity:
    name: Update GitHub Activity section in README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Recent GitHub Activity - Profile Readme
        uses: Readme-Workflows/recent-activity@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
