name: Update Awesome Stars

on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch:

jobs:
  update-awesome-stars:
    name: Update the AWESOME-STARS.md file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - run: pip install starred
      - name: Update file
        run: starred --username ${{ github.repository_owner }} --sort --token ${{ secrets.GITHUB_TOKEN }} > AWESOME-STARS.md
      - name: Commit file
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add AWESOME-STARS.md
          git commit -m "docs[skip actions]: update awesome stars"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
