name: Update GitHub Activity

on:
  push:
    branches:
      - main
  schedule:
    - cron: '8 */3 * * *'
  workflow_dispatch:

jobs:
  update-github-activity:
    name: Update GitHub Activity section in README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
